#!/bin/bash
# Released sowohl Shop- als auch sonstige Artefakte mit Hilfe des CI Servers
unset JAVA_TOOL_OPTIONS
set -eu
trace_setup() {
  echo "$(date '+%H:%M:%S.000') shell-script - $1" >> ${HOME}/.release.log
}
trace_setup "init scripting"
echo -n "I: Starting release vm .."
argLine="${*:-}"

if [[ -n $(echo "${argLine}" | egrep -- "--replace") ]]; then
  pushd .  > /dev/null
  cd $(dirname $0)
  release_jar=$(dirname $0)/target/scala-2.13/release.jar
  jar_out="$(java -jar ${release_jar} 2>&1 || true)"
  cmp_out="$(cmp ${release_jar} $(dirname $0)/release.jar 2>&1 || true)"
  if [[ $(echo "$jar_out" | egrep -v "^Error: ") != "" ]] && [[ $(echo "$cmp_out" | egrep "differ") != "" ]]; then
    ls -l ${release_jar}
    ls -lh ${release_jar}
    cp -v ${release_jar} $(dirname $0)/release.jar
  fi
  popd > /dev/null
fi
release_jar=$(dirname $0)/release.jar
if command -v tput >/dev/null; then
  terminal_cols=$(tput cols)
else
  terminal_cols="80"
fi

if $(uname | egrep -iq "cygwin"); then
  os="Cygwin"
else
  os="$(uname)"
fi
trace_setup "start vm"
if [[ "${os}" = "Cygwin" ]]; then
  set +e
  java -Dfile.encoding=UTF-8 -jar $(cygpath -aw ${release_jar}) "$(cygpath -aw $(dirname $0))" "$(cygpath -aw $(pwd))" "${os}" "${TERM}" "${terminal_cols}" ${argLine}
  java_exit=$?
  set -e
else
  set +e
  java -Dfile.encoding=UTF-8 -jar ${release_jar} "$(dirname $0)" "$(pwd)" "${os}" "${TERM}" "${terminal_cols}" ${argLine}
  java_exit=$?
  set -e
fi
if [[ ${java_exit} -eq 99 ]]; then
  if [[ ${ISHOP_RELEASE_UPDATE_EXEC_AUTO:-0} -eq 1 ]]; then
    ps -fp $$ | egrep -v "COMMAND"
  fi
  if [[ ${ISHOP_RELEASE_UPDATE_AUTO:-0} -eq 1 ]]; then
    update_cmd=$(java -Dfile.encoding=UTF-8 -jar ${release_jar} "$(dirname $0)" "$(pwd)" "${os}" "${TERM}" "${terminal_cols}" --show-update-cmd)
    echo "I: starting self update"
    eval "${update_cmd}"
    if [[ ${ISHOP_RELEASE_UPDATE_EXEC_AUTO:-0} -eq 1 ]]; then
      self_cmd="$0 $argLine"
      eval "${self_cmd}"
    elif [[ ${ISHOP_RELEASE_UPDATE_EXEC_AUTO:-0} -eq 0 ]]; then
      echo "I: self update completed, please restart release"
      echo "I: release supports self execution: add 'export ISHOP_RELEASE_UPDATE_EXEC_AUTO=1' to your e.g. .bash_profile to test it"
    fi
  elif [[ ${ISHOP_RELEASE_UPDATE_AUTO:-0} -eq 0 ]]; then
    echo "I: release supports self updates: add 'export ISHOP_RELEASE_UPDATE_AUTO=1' to your e.g. .bash_profile to test it"
  fi
fi

