package release

import release.PomMod.{Dep, PluginDep, PluginExec, PomRef}

object Anyshop1Deps {

  def plugins(): Seq[PluginDep] = Seq(
    PluginDep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT:pom"),
      "org.jacoco", "jacoco-maven-plugin", "", Seq(PluginExec("default-prepare-agent", Seq("prepare-agent"), "", Map()), PluginExec("default-report", Seq("report"), "prepare-package", Map())),
      Seq("plugin", "plugins", "build", "project")),
    PluginDep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT:pom"),
      "org.apache.maven.plugins", "maven-dependency-plugin", "2.8", Seq(PluginExec("pre-build-validate-tree", Seq("tree"), "validate", Map("outputFile" -> "dep.tree")), PluginExec("pre-build-validate-list", Seq("list"), "validate", Map("outputFile" -> "dep.list", "sort" -> "true"))),
      Seq("plugin", "plugins", "build", "project")),
    PluginDep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT:pom"),
      "com.novomind.maven", "zkm-maven-plugin", "", Seq(PluginExec("", Seq(), "", Map())),
      Seq("plugin", "plugins", "build", "project")),
    PluginDep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT:pom"),
      "org.apache.maven.plugins", "maven-checkstyle-plugin", "2.17", Seq(PluginExec("validate", Seq("check"), "validate", Map("configLocation" -> "checkstyle.xml", "includeTestSourceDirectory" -> "true", "consoleOutput" -> "true", "encoding" -> "UTF-8", "failsOnError" -> "true"))),
      Seq("plugin", "plugins", "build", "project")),
    PluginDep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT:pom"),
      "org.codehaus.mojo", "aspectj-maven-plugin", "1.8", Seq(PluginExec("", Seq("compile", "test-compile"), "", Map())),
      Seq("plugin", "plugins", "pluginManagement", "build", "project")),
    PluginDep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT:pom"),
      "", "maven-surefire-plugin", "", Seq(),
      Seq("plugin", "plugins", "build", "profile", "profiles", "project")),
    PluginDep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT:pom"),
      "", "maven-failsafe-plugin", "2.19.1", Seq(PluginExec("", Seq("integration-test", "verify"), "", Map())),
      Seq("plugin", "plugins", "build", "profile", "profiles", "project")),
    PluginDep(PomRef("com.novomind.ishop.shops:anyshop:27.0.0-SNAPSHOT:war"),
      "org.apache.maven.plugins", "maven-compiler-plugin", "", Seq(),
      Seq("plugin", "plugins", "build", "project"))
  )

  def snapshots(): Seq[Dep] = {
    Seq(
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "com.novomind.ishop.shops", "ishop-shop-parent", "27.0.0-SNAPSHOT", "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "com.novomind.ishop.core", "ishop-core-all", "27.1.2-SNAPSHOT", "pom", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "com.novomind.ishop.core", "ishop-core-all-tests", "27.1.2-SNAPSHOT", "pom", "test", "", ""),
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "com.novomind.ishop.shops-ext", "ishop-shops-ext-shop-base", "27.0.0-SNAPSHOT", "", "", "", ""),
      Dep(PomRef("anyshop-erp"),
        "com.novomind.ishop.core", "ishop-core-projects", "27.1.2-SNAPSHOT", "pom", "import", "", ""),
      Dep(PomRef("anyshop-erp"),
        "com.novomind.ishop.shops.anyshop", "anyshop-commons", "27.0.0-SNAPSHOT", "", "", "", ""),
      Dep(PomRef("anyshop-erp"),
        "com.novomind.ishop.shops.anyshop", "anyshop-commons", "27.0.0-SNAPSHOT", "", "test", "", "tests"),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "com.novomind.ishop.core", "ishop-core-projects", "27.1.2-SNAPSHOT", "pom", "import", "", ""),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "com.novomind.ishop.shops.anyshop", "anyshop-commons", "27.0.0-SNAPSHOT", "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "com.novomind.ishop.shops.anyshop", "anyshop-commons", "27.0.0-SNAPSHOT", "", "test", "", "tests"),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "", "", "", "pom"),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "", "test", "", "pom"),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "com.novomind.ishop.backoffice", "bo-services", "27.1.2-SNAPSHOT", "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "com.novomind.ishop.backoffice", "bo-core", "27.1.2-SNAPSHOT", "", "", "", "")
    )
  }

  def selfMod(): Seq[Dep] = Seq(
    Dep(PomRef("X"),
      "com.novomind.ishop.shops", "anyshop", "27.0.0-SNAPSHOT", "", "", "", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops", "anyshop", "27.0.0-SNAPSHOT", "", "", "war", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops", "anyshop", "27.0.0-SNAPSHOT", "", "", "war", "sources"),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops", "anyshop", "27.0.0-SNAPSHOT", "", "", "war", "tests"),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops", "anyshop", "27.0.0-SNAPSHOT", "", "test", "", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops", "anyshop", "27.0.0-SNAPSHOT", "", "test", "", "tests"),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops", "anyshop", "27.0.0-SNAPSHOT", "", "test", "war", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops", "anyshop", "27.0.0-SNAPSHOT", "", "test", "war", "tests"),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops", "anyshop", "27.0.0-SNAPSHOT", "pom", "", "", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops", "anyshop", "27.0.0-SNAPSHOT", "pom", "", "war", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops", "anyshop", "27.0.0-SNAPSHOT", "pom", "", "war", "sources"),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops", "anyshop", "27.0.0-SNAPSHOT", "pom", "", "war", "tests"),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops", "anyshop", "27.0.0-SNAPSHOT", "pom", "runtime", "", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops", "anyshop", "27.0.0-SNAPSHOT", "pom", "test", "", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops", "anyshop", "27.0.0-SNAPSHOT", "pom", "test", "", "tests"),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops", "anyshop", "27.0.0-SNAPSHOT", "pom", "test", "war", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops", "anyshop", "27.0.0-SNAPSHOT", "pom", "test", "war", "tests"),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops", "anyshop", "27.0.0-SNAPSHOT", "war", "runtime", "", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "", "", "", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "", "", "", "sources"),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "", "", "", "tests"),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "", "test", "", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "", "test", "", "tests"),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "pom", "", "", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "pom", "", "", "sources"),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "pom", "", "", "tests"),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "pom", "runtime", "", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "pom", "test", "", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "pom", "test", "", "tests"),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "war", "runtime", "", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-projects", "27.0.0-SNAPSHOT", "", "", "", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-projects", "27.0.0-SNAPSHOT", "", "", "pom", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-projects", "27.0.0-SNAPSHOT", "", "", "pom", "sources"),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-projects", "27.0.0-SNAPSHOT", "", "", "pom", "tests"),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-projects", "27.0.0-SNAPSHOT", "", "test", "", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-projects", "27.0.0-SNAPSHOT", "", "test", "", "tests"),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-projects", "27.0.0-SNAPSHOT", "", "test", "pom", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-projects", "27.0.0-SNAPSHOT", "", "test", "pom", "tests"),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-projects", "27.0.0-SNAPSHOT", "pom", "", "", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-projects", "27.0.0-SNAPSHOT", "pom", "", "pom", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-projects", "27.0.0-SNAPSHOT", "pom", "", "pom", "sources"),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-projects", "27.0.0-SNAPSHOT", "pom", "", "pom", "tests"),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-projects", "27.0.0-SNAPSHOT", "pom", "runtime", "", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-projects", "27.0.0-SNAPSHOT", "pom", "test", "", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-projects", "27.0.0-SNAPSHOT", "pom", "test", "", "tests"),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-projects", "27.0.0-SNAPSHOT", "pom", "test", "pom", ""),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-projects", "27.0.0-SNAPSHOT", "pom", "test", "pom", "tests"),
    Dep(PomRef("X"),
      "com.novomind.ishop.shops.anyshop", "anyshop-projects", "27.0.0-SNAPSHOT", "war", "runtime", "", "")
  )

  def selfVersion(version: String): Seq[Dep] = {
    Seq(
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:" + version),
        "com.novomind.ishop.shops.anyshop", "anyshop-projects", version, "", "", "pom", ""),
      Dep(PomRef("anyshop-erp"),
        "com.novomind.ishop.shops.anyshop", "anyshop-erp", version, "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "com.novomind.ishop.shops", "anyshop", version, "", "", "war", "")
    )
  }

  def self(): Seq[Dep] = selfVersion("27.0.0-SNAPSHOT")

  def ownDeps(): Seq[Dep] = Seq(
    Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
      "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "", "", "", ""),
    Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-erp:27.0.0-SNAPSHOT"),
      "com.novomind.ishop.shops.anyshop", "anyshop-projects", "27.0.0-SNAPSHOT", "", "", "", ""),
    Dep(PomRef("anyshop-erp"),
      "com.novomind.ishop.shops.anyshop", "anyshop-commons", "27.0.0-SNAPSHOT", "", "", "", ""),
    Dep(PomRef("anyshop-erp"),
      "com.novomind.ishop.shops.anyshop", "anyshop-commons", "27.0.0-SNAPSHOT", "", "test", "", "tests"),
    Dep(PomRef("com.novomind.ishop.shops:anyshop:27.0.0-SNAPSHOT"),
      "com.novomind.ishop.shops.anyshop", "anyshop-projects", "27.0.0-SNAPSHOT", "", "", "", ""),
    Dep(PomRef("com.novomind.ishop.shops:anyshop"),
      "com.novomind.ishop.shops.anyshop", "anyshop-commons", "27.0.0-SNAPSHOT", "", "", "", ""),
    Dep(PomRef("com.novomind.ishop.shops:anyshop"),
      "com.novomind.ishop.shops.anyshop", "anyshop-commons", "27.0.0-SNAPSHOT", "", "test", "", "tests"),
    Dep(PomRef("com.novomind.ishop.shops:anyshop"),
      "com.novomind.ishop.shops.anyshop", "anyshop-erp", "", "", "", "", ""),
    Dep(PomRef("com.novomind.ishop.shops:anyshop"),
      "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "", "test", "", ""),
    Dep(PomRef("com.novomind.ishop.shops:anyshop"),
      "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "", "test", "", "tests"),
    Dep(PomRef("com.novomind.ishop.shops:anyshop"),
      "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "", "", "", "pom"),
    Dep(PomRef("com.novomind.ishop.shops:anyshop"),
      "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "", "test", "", "pom")
  )

  def all(): Seq[Dep] = {
    Seq(
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "com.novomind.ishop.shops", "ishop-shop-parent", "27.0.0-SNAPSHOT", "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "org.apache.httpcomponents", "httpclient", "4.5.1", "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "org.apache.commons", "commons-lang3", "3.4", "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "io.reactivex", "rxjava", "1.0.12", "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "com.netflix.hystrix", "hystrix-core", "1.4.12", "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "com.github.dreamhead", "moco-core", "0.10.2", "", "test", "", ""),
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "com.novomind.ishop.core", "ishop-core-all", "27.1.2-SNAPSHOT", "pom", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "com.novomind.ishop.core", "ishop-core-all-tests", "27.1.2-SNAPSHOT", "pom", "test", "", ""),
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "com.novomind.ishop.shops-ext", "ishop-shops-ext-shop-base", "27.0.0-SNAPSHOT", "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "org.apache.httpcomponents", "httpclient", "", "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "org.apache.commons", "commons-lang3", "", "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "com.github.dreamhead", "moco-core", "", "", "test", "", ""),
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "com.netflix.hystrix", "hystrix-core", "", "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "io.reactivex", "rxjava", "", "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "com.novomind.ishop.core", "ishop-core-all", "", "pom", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "com.novomind.ishop.core", "ishop-core-all-tests", "", "pom", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "org.aspectj", "aspectjrt", "1.8.8", "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-projects:27.0.0-SNAPSHOT"),
        "org.aspectj", "aspectjtools", "1.8.8", "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops.anyshop:anyshop-erp:27.0.0-SNAPSHOT"),
        "com.novomind.ishop.shops.anyshop", "anyshop-projects", "27.0.0-SNAPSHOT", "", "", "", ""),
      Dep(PomRef("anyshop-erp"),
        "com.novomind.ishop.core", "ishop-core-projects", "27.1.2-SNAPSHOT", "pom", "import", "", ""),
      Dep(PomRef("anyshop-erp"),
        "com.novomind.ishop.shops.anyshop", "anyshop-commons", "27.0.0-SNAPSHOT", "", "", "", ""),
      Dep(PomRef("anyshop-erp"),
        "com.novomind.ishop.shops.anyshop", "anyshop-commons", "27.0.0-SNAPSHOT", "", "test", "", "tests"),
      Dep(PomRef("anyshop-erp"),
        "com.novomind.ishop.core", "ishop-core-all", "", "pom", "", "", ""),
      Dep(PomRef("anyshop-erp"),
        "com.novomind.ishop.core", "ishop-core-all-tests", "", "pom", "test", "", ""),
      Dep(PomRef("com.novomind.ishop.shops:anyshop:27.0.0-SNAPSHOT"),
        "com.novomind.ishop.shops.anyshop", "anyshop-projects", "27.0.0-SNAPSHOT", "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "com.novomind.ishop.core", "ishop-core-projects", "27.1.2-SNAPSHOT", "pom", "import", "", ""),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "com.novomind.ishop.shops.anyshop", "anyshop-commons", "27.0.0-SNAPSHOT", "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "com.novomind.ishop.shops.anyshop", "anyshop-commons", "27.0.0-SNAPSHOT", "", "test", "", "tests"),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "com.novomind.ishop.shops.anyshop", "anyshop-erp", "", "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "", "test", "", ""),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "", "test", "", "tests"),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "", "", "", "pom"),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "com.novomind.ishop.shops.anyshop", "anyshop-erp", "27.0.0-SNAPSHOT", "", "test", "", "pom"),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "com.novomind.ishop.core", "ishop-core-all", "", "pom", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "com.novomind.ishop.core", "ishop-core-all-tests", "", "pom", "test", "", ""),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "com.novomind.ishop.shops-ext", "ishop-shops-ext-shop-base", "", "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "com.novomind.ishop.backoffice", "bo-services", "27.1.2-SNAPSHOT", "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "com.novomind.ishop.backoffice", "bo-core", "27.1.2-SNAPSHOT", "", "", "", ""),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "javax.servlet.jsp", "jsp-api", "2.2", "", "provided", "", ""),
      Dep(PomRef("com.novomind.ishop.shops:anyshop"),
        "javax.el", "javax.el-api", "3.0.0", "", "test", "", "")
    )
  }
}
